import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electron', {
  getThemeCss: () => ipcRenderer.invoke('theme:get-css'),
  listDir: (path: string) => ipcRenderer.invoke('fs:list-dir', path),
  getParentPath: (path: string) => ipcRenderer.invoke('fs:get-parent', path),
  getHomePath: () => ipcRenderer.invoke('fs:get-home'),
  getPlaces: () => ipcRenderer.invoke('fs:get-places'),
  copyFile: (source: string, dest: string) => ipcRenderer.invoke('fs:copy', source, dest),
  moveFile: (source: string, dest: string) => ipcRenderer.invoke('fs:move', source, dest),
  trashFile: (path: string) => ipcRenderer.invoke('fs:trash', path),
  renameFile: (oldPath: string, newPath: string) => ipcRenderer.invoke('fs:rename', oldPath, newPath),
  createDirectory: (path: string) => ipcRenderer.invoke('fs:mkdir', path),
  openPath: (path: string) => ipcRenderer.invoke('fs:open', path),
  extractFile: (path: string) => ipcRenderer.invoke('fs:extract', path),
  getApps: () => ipcRenderer.invoke('system:get-apps'),
  openWith: (exec: string, path: string) => ipcRenderer.invoke('system:open-with', exec, path),
  terminalOpen: (path: string) => ipcRenderer.invoke('terminal:open', path),
  cdTerminal: (path: string) => ipcRenderer.invoke('terminal:cd', path),
  openFileDialog: () => ipcRenderer.invoke('dialog:open-file'),
  readFile: (path: string) => ipcRenderer.invoke('fs:read-file', path),
  startDrag: (path: string, iconPath?: string) => ipcRenderer.send('dnd:start', path, iconPath),
  getStorageUsage: () => ipcRenderer.invoke('system:get-storage-usage'),
  getStartupPath: () => ipcRenderer.invoke('app:get-startup-path'),
  exists: (path: string) => ipcRenderer.invoke('fs:exists', path),
  setIcon: (iconPath: string) => ipcRenderer.invoke('window:set-icon', iconPath),
  search: (dir: string, query: string, options?: any) => ipcRenderer.invoke('system:search', dir, query, options),
  getDirectorySize: (path: string) => ipcRenderer.invoke('system:get-directory-size', path),
  getDrives: () => ipcRenderer.invoke('system:get-drives'),
});
